### PR TITLE
Feature: Update Mixpanel tracking

### PR DESCRIPTION
**Pull request by clemens**
/cc @moritzplassnig @AlexTi

### CODE REVIEW

**Comment by moritzplassnig** [comment]
@clemens I would put the whole advent calendar offline. It's okay for Manny as well.

**Comment by clemens** [comment]
No idea how to do this or if I even have access – so someone else must do it. :)

**Comment by clemenshelm** [comment]
@moritzplassnig Nooooooooooo!

**Comment by moritzplassnig** [comment]
@clemenshelm "New" Clemens is deleting Stuff from "old" Clemens - I'm sorry :D

**Comment by jschley** [comment]
@clemens I will kill the advent calendar site

**Comment by clemens** [comment]
@jschley Just close this PR once you took it offline, please. :)

**Comment by jschley** [comment]
shut down advent calendar site

**Pull request closed without merging**
